services:
  squidward:
    image: squidwardproxy/squidward
    container_name: 'squidward'
    hostname: remnawave
    restart: unless-stopped
    ports:
      - '127.0.0.1:4000:4000'
    env_file:
      - .env
    networks:
      - squidward-network-internal
      - squidward-network-external
    depends_on:
      squidward-db:
        condition: service_healthy
      squidward-redis:
        condition: service_healthy

  squidward-db:
    image: postgres:17.6-bookworm
    container_name: squidward-db
    hostname: squidward-db
    restart: unless-stopped
    environment:
      POSTGRES_HOST_FILE: /run/secrets/postgres_host
      POSTGRES_PORT_FILE: /run/secrets/postgres_port
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      TZ: ${TZ}
      PGTZ: ${TZ}
    expose:
      - 5432
    volumes:
      - squidward-db-vol:/var/lib/postgresql/data
    networks:
      - squidward-network-internal
    secrets:
      - postgres_host
      - postgres_port
      - postgres_db
      - postgres_user
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user) -d $$(cat /run/secrets/postgres_db)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  squidward-redis:
    image: valkey/valkey:9.0-alpine3.22
    container_name: squidward-redis
    hostname: squidward-redis
    restart: unless-stopped
    networks:
      - squidward-network-internal
      - squidward-network-external # DEV ONLY
    expose:
      - '6379'
    volumes:
      - squidward-redis-vol:/data
    entrypoint: "/bin/sh -c \"valkey-server --requirepass $$(cat /run/secrets/valkey_password)\""
    secrets:
      - valkey_password
    healthcheck:
      test: [ 'CMD', 'valkey-cli', 'ping' ]
      interval: 3s
      timeout: 10s
      retries: 3

volumes:
  squidward-db-vol:
    driver: local
    external: false
    name: squidward-db-vol
  squidward-redis-vol:
    driver: local
    external: false
    name: squidward-redis-vol

networks:
  squidward-network-internal:
    name: squidward-network-internal
    internal: true
    external: false
  squidward-network-external:
    name: squidward-network-external
    driver: bridge
    external: true

secrets:
  postgres_host:
    environment: POSTGRES_HOST
  postgres_port:
    environment: POSTGRES_PORT
  postgres_db:
    environment: POSTGRES_DB
  postgres_user:
    environment: POSTGRES_USER
  postgres_password:
    environment: POSTGRES_PASSWORD
  valkey_password:
    environment: REDIS_PASSWORD