export enum QUEUES {
    NODE_HEALTH_CHECK = 'NODE_HEALTH_CHECK',
    NODE_RESTART = 'NODE_RESTART_QUEUE',
    NODE_START = 'NODE_START_QUEUE',
    NODE_STOP = 'NODE_STOP_QUEUE',
    NODES_ADD_USER = 'NODES_ADD_USER_QUEUE',
    NODES_REMOVE_USER = 'NODES_REMOVE_USER_QUEUE',
    NODES_UPDATE_USER = 'NODES_UPDATE_USER_QUEUE',
}