import * as CONTROLLERS from './controllers';

export const ROOT = '/api' as const;

export const REST_API = {
    NODES: {
        CREATE: `${ROOT}/${CONTROLLERS.NODES_CONTROLLER}/${CONTROLLERS.NODES_ROUTES.CREATE}`,
        UPDATE: (uuid: string) => `${ROOT}/${CONTROLLERS.NODES_CONTROLLER}/${CONTROLLERS.NODES_ROUTES.UPDATE(uuid)}`,
        REMOVE: (uuid: string) => `${ROOT}/${CONTROLLERS.NODES_CONTROLLER}/${CONTROLLERS.NODES_ROUTES.REMOVE(uuid)}`,
        LIST: `${ROOT}/${CONTROLLERS.NODES_CONTROLLER}/${CONTROLLERS.NODES_ROUTES.LIST}`,
        START:  (uuid: string) => `${ROOT}/${CONTROLLERS.NODES_CONTROLLER}/${CONTROLLERS.NODES_ROUTES.START(uuid)}`,
        STOP:  (uuid: string) => `${ROOT}/${CONTROLLERS.NODES_CONTROLLER}/${CONTROLLERS.NODES_ROUTES.STOP(uuid)}`,
        RESTART:  (uuid: string) => `${ROOT}/${CONTROLLERS.NODES_CONTROLLER}/${CONTROLLERS.NODES_ROUTES.RESTART(uuid)}`,
        KEYGEN: `${ROOT}/${CONTROLLERS.NODES_CONTROLLER}/${CONTROLLERS.NODES_ROUTES.KEYGEN}`,
    },
    USERS: {
        CREATE: `${ROOT}/${CONTROLLERS.USERS_CONTROLLER}/${CONTROLLERS.USERS_ROUTES.CREATE}`,
        UPDATE: (uuid: string) => `${ROOT}/${CONTROLLERS.USERS_CONTROLLER}/${CONTROLLERS.USERS_ROUTES.UPDATE(uuid)}`,
        REMOVE: (uuid: string) => `${ROOT}/${CONTROLLERS.USERS_CONTROLLER}/${CONTROLLERS.USERS_ROUTES.REMOVE(uuid)}`,
        LIST: `${ROOT}/${CONTROLLERS.USERS_CONTROLLER}/${CONTROLLERS.USERS_ROUTES.LIST}`,
    },
    CONFIGS: {
        CREATE: `${ROOT}/${CONTROLLERS.CONFIGS_CONTROLLER}/${CONTROLLERS.CONFIGS_ROUTES.CREATE}`,
        UPDATE: (uuid: string) => `${ROOT}/${CONTROLLERS.CONFIGS_CONTROLLER}/${CONTROLLERS.CONFIGS_ROUTES.UPDATE(uuid)}`,
        REMOVE: (uuid: string) => `${ROOT}/${CONTROLLERS.CONFIGS_CONTROLLER}/${CONTROLLERS.CONFIGS_ROUTES.REMOVE(uuid)}`,
        GET_ONE: (uuid: string) => `${ROOT}/${CONTROLLERS.CONFIGS_CONTROLLER}/${CONTROLLERS.CONFIGS_ROUTES.GET_ONE(uuid)}`,
        LIST: `${ROOT}/${CONTROLLERS.CONFIGS_CONTROLLER}/${CONTROLLERS.CONFIGS_ROUTES.LIST}`,
    },
}