name: release.yml
on:
  push:
#    branches: [ "main" ]
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: NewTag
        id: tag
        uses: JinoArch/get-latest-tag@latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            squidwardproxy/squidward:latest
            squidwardproxy/squidward:${{ github.ref_name }}
          build-args: |
            CI=true

  release-backend-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: NewTag
        id: tag
        uses: JinoArch/get-latest-tag@latest

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Create contracts package
        run: |
          cd libs/contracts/
          npm pack
          mv squidward-contracts-*.tgz  ../../squidward-contracts.tgz

      - name: Upload Release Asset
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: squidward-contracts.tgz
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          append_body: true
          make_latest: true
          draft: false
          prerelease: false
          name: ${{ github.ref_name }}
          body: |
            # Squidward Panel v${{ github.ref_name }}

            ${{ env.CHANGELOG }}

            ### 📦 Artifacts
            - [squidward-contracts.tgz](https://github.com/spy-duck/squidward-backend/releases/download/${{ github.ref_name }}/squidward-contracts.tgz) - contracts package for frontend integration
